#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import sys
import time
import argparse

_DEFAULT_FORMAT = u"%Y%m%d"

if hasattr(datetime, 'strptime'):
    strptime = datetime.datetime.strptime
else:
    strptime = lambda date_string, format: datetime.datetime(*(time.strptime(date_string, format)[0:6]))

parser = argparse.ArgumentParser()
parser.add_argument("-s", "--start")
parser.add_argument("-e", "--end")
parser.add_argument("--step", type=int, default=1)
parser.add_argument("-f", "--format", default="%Y%m%d")
option = parser.parse_args(sys.argv[1:])

start = strptime(option.start, option.format)
end = strptime(option.end, option.format)

step = abs(option.step)
if start > end:
    step *= -1

delta = 0

while True:

    result = start + datetime.timedelta(days=delta)

    if result <= end <= start:
        break

    if start < end < result:
        break

    delta += step

    print result.strftime(option.format)

